# Coding Exercise number 5 - 29/8/2023
file = open("members.txt", "r")
members = file.readlines()
file.close()
new_member = input("Add the new member, in the form Name Surname: ")
members.append(new_member+"\n")
print(members)
file = open("members.txt", "w")
file.writelines(members)
file.close()
